import { useMemo, useState } from "react";
import { ArrowLeft, ArrowUpLeft, BriefcaseBusiness, Check, Code2, ExternalLink, Filter, Layers3, Mail, Menu, Play, Sparkles, X, Zap } from "lucide-react";

type Category = "الكل" | "ذكاء اصطناعي" | "تعليم" | "ألعاب" | "إبداع";
type Project = { id:string; no:string; title:string; en:string; category:Exclude<Category,"الكل">; detail:string; tags:string[]; image:string; tone:string; source:string; featured?:boolean };

const projects: Project[] = [
 {id:"zai",no:"01",title:"Z.ai",en:"Advanced AI Chatbot & Agent",category:"ذكاء اصطناعي",detail:"مساعد ذكي متقدم powered by GLM-5.3-Flash، صُمّم لتحويل الحوار إلى أفعال وتدفقات عمل عملية.",tags:["GLM-5.3-Flash","AI Agent"],image:"/assets/ai-signal.jpg",tone:"cyan",source:"https://drive.google.com/drive/folders/1LW2Iy9ylJHIsgN_bcJg8a_Q68w_NqWzE?usp=drive_link",featured:true},
 {id:"wardrobe",no:"02",title:"خزانة ملابس",en:"High-tech wardrobe film",category:"إبداع",detail:"فيديو بصري يجمع بين توليد المشهد، الإخراج الإبداعي، وتصميم الإيقاع لصناعة لحظة تقنية قابلة للتذكر.",tags:["AI Video","Art Direction"],image:"/assets/hero-orbit.jpg",tone:"violet",source:"https://drive.google.com/drive/folders/1tj3kGjdfiwMwq5Ry_6cxz5UoJaRikbjK?usp=sharing"},
 {id:"iq",no:"03",title:"IQ Arena",en:"Interactive intelligence test",category:"تعليم",detail:"ساحة اختبار ذكاء تفاعلية توازن بين وضوح الأسئلة، سرعة التفاعل، وإحساس التقدم.",tags:["Gamification","Assessment"],image:"/assets/playful-letters.jpg",tone:"orange",source:"https://drive.google.com/drive/folders/1tj3kGjdfiwMwq5Ry_6cxz5UoJaRikbjK?usp=sharing"},
 {id:"letters",no:"04",title:"حروف ومرح",en:"Learn Arabic through play",category:"تعليم",detail:"تجربة تعليمية مرحة تعرّف الأطفال إلى الحروف العربية من خلال اللعب والتفاعل المباشر.",tags:["Arabic Learning","Kids UX"],image:"/assets/playful-letters.jpg",tone:"orange",source:"https://drive.google.com/drive/folders/1tj3kGjdfiwMwq5Ry_6cxz5UoJaRikbjK?usp=sharing"},
 {id:"nuskha",no:"05",title:"نُسخ",en:"Your library, your voice",category:"إبداع",detail:"مكتبة شخصية بصوت صاحبها، تربط بين المحتوى الصوتي والذاكرة الشخصية داخل واجهة هادئة.",tags:["Voice UX","Library"],image:"/assets/hero-orbit.jpg",tone:"violet",source:"https://drive.google.com/drive/folders/1LW2Iy9ylJHIsgN_bcJg8a_Q68w_NqWzE?usp=drive_link"},
 {id:"bomberman",no:"06",title:"Bomberman Neon Arcade",en:"Modern arcade game",category:"ألعاب",detail:"إعادة تخيل نيون للعبة بومبرمان: سرعة، متاهة، وانفجارات محسوبة بروح الأركيد.",tags:["Game Design","Neon UI"],image:"/assets/neon-arcade.jpg",tone:"pink",source:"https://drive.google.com/drive/folders/1xI3DZ2w_q0Oz6Kb32-FJ6G92B2mzrLIQ?usp=sharing",featured:true}
];
const filters:[Category,string][] = [["الكل","06"],["ذكاء اصطناعي","01"],["تعليم","02"],["ألعاب","01"],["إبداع","02"]];
const Label=({no,children}:{no:string;children:React.ReactNode})=><div className="section-label"><span>{no}</span><i/><span>{children}</span></div>;

export default function Home(){
 const [filter,setFilter]=useState<Category>("الكل"); const [modal,setModal]=useState<Project|null>(null); const [menu,setMenu]=useState(false); const [tour,setTour]=useState(false);
 const visible=useMemo(()=>filter==="الكل"?projects:projects.filter(p=>p.category===filter),[filter]);
 const go=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:"smooth"});setMenu(false)};
 return <main dir="rtl" className="site-shell"><div className="ambient ambient-one"/><div className="ambient ambient-two"/><div className="grain"/>
 <header className="topbar"><button className="brand-mark" onClick={()=>go("top")}><b>ح</b><span><strong>HAZEM</strong><small>DIGITAL LAB</small></span></button><nav className={menu?"nav-links mobile-open":"nav-links"}><button onClick={()=>go("work")}><em>01</em>المشاريع</button><button onClick={()=>go("about")}><em>02</em>عنّي</button><button onClick={()=>go("contact")}><em>03</em>تواصل</button></nav><div className="top-actions"><a href="mailto:hazem.now55@gmail.com" className="availability"><span/> متاح لمشاريع جديدة</a><button className="menu-button" onClick={()=>setMenu(!menu)}>{menu?<X size={18}/>:<Menu size={18}/>}</button></div></header>
 <section id="top" className="hero-section"><div className="hero-grid-lines"/><div className="hero-copy"><div className="hero-kicker"><Sparkles size={15}/> مختبر أفكار رقمية من الأردن</div><h1>أصنع تجارب<br/><span>تتجاوز الشاشة.</span></h1><p>أنا <strong>حازم محمد خطابنة</strong> — محاضر علوم حاسوب ومصمم تجارب رقمية، أتنقل بين الذكاء الاصطناعي، التعليم، الألعاب، والصورة لأصنع أشياء يصعب نسيانها.</p><div className="hero-actions"><button className="primary-button" onClick={()=>go("work")}>استكشف الأعمال <ArrowLeft size={17}/></button><button className={tour?"play-button playing":"play-button"} onClick={()=>setTour(!tour)}><span className="play-icon">{tour?<span className="pause-bars"/>:<Play size={13} fill="currentColor"/>}</span>{tour?"إيقاف الجولة":"شغّل الجولة"}</button></div></div><div className="hero-art"><div className="hero-image"/><div className="orbit orbit-large"/><div className="orbit orbit-small"/><div className="signal signal-one"/><div className="signal signal-two"/><div className="node node-one"/><div className="node node-two"/><div className="hero-stamp">SCROLL <ArrowUpLeft size={15}/></div><div className="hero-code"><span>01</span><span>SYS / CREATE</span><span>✓</span></div></div><div className="hero-meta"><div><small>المجال</small><b>Code × Curiosity</b></div><div><small>الإصدار</small><b>Portfolio / 2026</b></div><div className="scroll-hint"><span/> مرّر لاكتشاف الفكرة التالية</div></div></section>
 <section id="work" className="page-section work-section"><div className="section-head"><div><Label no="01">المختبر / المشاريع</Label><h2>أفكار خرجت<br/><i>من المختبر.</i></h2></div><p>كل مشروع هنا محاولة لصنع جسر جديد بين التقنية والإنسان — من سؤال بسيط إلى تجربة كاملة.</p></div><div className="filter-bar"><strong><Filter size={15}/> تصفّح حسب النوع</strong><div>{filters.map(([name,count])=><button key={name} className={filter===name?"active":""} onClick={()=>setFilter(name)}>{name} <small>{count}</small></button>)}</div></div><div className="projects-grid">{visible.map((p,i)=><article key={p.id} className={p.featured?"project-card featured":"project-card"} style={{"--delay":`${i*60}ms`} as React.CSSProperties} onClick={()=>setModal(p)}><div className={`project-image ${p.tone}`} style={{backgroundImage:`url(${p.image})`}}><div className="project-overlay"/><div className="project-topline"><span>{p.no} / 06</span><span>2026</span></div><div className="project-hover">عرض التفاصيل <ArrowLeft size={17}/></div><label>{p.category}</label></div><div className="project-info"><div><h3>{p.title}</h3><p>{p.en}</p></div><ArrowUpLeft size={20}/></div><div className="project-tags">{p.tags.map(tag=><span key={tag}>{tag}</span>)}</div></article>)}</div></section>
 <section id="about" className="page-section about-section"><aside><Label no="02">خلف الكود</Label><div>ABOUT / 02</div></aside><div className="about-main"><h2>أحوّل الفضول<br/><span>إلى شيء قابل للاستخدام.</span></h2><div className="about-columns"><p>بدأت رحلتي من علوم الحاسوب، ثم أخذتني قاعات التدريب إلى تصميم التجارب التي تجعل المعرفة أسهل وأقرب. اليوم أعمل عند نقطة التقاء التعليم، الذكاء الاصطناعي، والإبداع البصري.</p><p>أحب الأفكار التي تبدأ كسؤال صغير، ثم تنمو لتصبح منتجًا أو لعبة أو مشهدًا يترك أثرًا. أتعامل مع كل شاشة كأنها مساحة سرد — فيها إيقاع، وضوح، ومفاجأة محسوبة.</p></div><div className="credentials"><div><em>01</em><BriefcaseBusiness size={18}/><span><b>خبرة تعليمية</b><small>أكثر من 10 سنوات في تدريس علوم الحاسوب</small></span></div><div><em>02</em><Code2 size={18}/><span><b>عقلية تقنية</b><small>Java · C++ · HTML · SQL · CCNA</small></span></div><div><em>03</em><Layers3 size={18}/><span><b>مساحات متعددة</b><small>AI · ألعاب · صوت · تعليم · سرد بصري</small></span></div></div></div></section>
 <section className="page-section manifesto"><strong>“</strong><div><p>لا أبني صفحات فقط،<br/><b>أبني سببًا للعودة.</b></p><small>— حازم محمد خطابنة</small></div><div className="manifesto-orbit"><Zap size={22}/> KEEP<br/>EXPLORING</div></section>
 <section id="contact" className="page-section contact"><Label no="03">نبدأ من هنا</Label><div className="contact-grid"><div><h2>فكرة في بالك؟<br/><i>خلّنا نحرّكها.</i></h2><p>للتعاون، التدريس، أو مشروع يريد أن يخرج عن المألوف.</p></div><a className="contact-card" href="mailto:hazem.now55@gmail.com"><span><Mail size={20}/></span><label>أرسل رسالة<strong>hazem.now55@gmail.com</strong></label><ArrowUpLeft size={20}/></a></div><footer><span>© 2026 HAZEM DIGITAL LAB</span><span>MADE WITH CURIOSITY / AMMAN</span><a href="https://drive.google.com/document/d/1_TsbarR5Xiot3jjqudcZB7eahedKHEwm/edit" target="_blank" rel="noreferrer">السيرة الذاتية <ExternalLink size={12}/></a></footer></section><div className="site-footer"><span>HAZEM / 2026</span><span>تجارب رقمية، بلمسة إنسانية.</span><span>↑</span></div>
 {modal&&<div className="modal-backdrop" onClick={()=>setModal(null)}><div className="project-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setModal(null)}><X size={18}/></button><div className={`modal-image ${modal.tone}`} style={{backgroundImage:`url(${modal.image})`}}><div className="project-overlay"/><span>{modal.no} / CASE STUDY</span></div><div className="modal-content"><small>{modal.category} · 2026</small><h2>{modal.title}</h2><i>{modal.en}</i><p>{modal.detail}</p><div className="modal-tags">{modal.tags.map(tag=><span key={tag}><Check size={12}/> {tag}</span>)}</div><a href={modal.source} target="_blank" rel="noreferrer">افتح المصدر <ExternalLink size={15}/></a></div></div></div>}</main>;
}
