import { useMemo, useState } from "react";
import { ArrowLeft, Briefcase, Check, ChevronLeft, FileText, Filter, Mail, Menu, Play, X } from "lucide-react";

type Category = "الكل" | "ذكاء اصطناعي" | "فيديو" | "تعليم" | "ألعاب";
type Project = { id: string; number: string; title: string; subtitle: string; category: Exclude<Category, "الكل">; description: string; tags: string[]; cover: string; kind: "iframe" | "video" | "image"; asset: string };

const projects: Project[] = [
  { id: "zai", number: "01", title: "Z.ai - Advanced AI Chatbot & Agent powered by GLM-5.3-Flash", subtitle: "مساعد ذكاء اصطناعي ووكلاء رقميون", category: "ذكاء اصطناعي", description: "تجربة مباشرة لمساعد ذكي متقدم مدعوم بـ GLM-5.3-Flash، تجمع بين الحوار والتفكير وتنفيذ المهام.", tags: ["GLM-5.3-Flash", "AI Agent"], cover: "/assets/ai-signal.jpg", kind: "iframe", asset: "/projects/zai.html" },
  { id: "wardrobe", number: "02", title: "تصميم فيديو خزانة ملابس بتقنية عالية - Manus", subtitle: "فيديو بصري من Manus", category: "فيديو", description: "فيديو إبداعي يعرض تصورًا بصريًا لخزانة ملابس ذكية، مع معالجة سينمائية وإخراج بصري مولد بالذكاء الاصطناعي.", tags: ["AI Video", "Art Direction"], cover: "/projects/wardrobe-poster.jpg", kind: "video", asset: "/projects/wardrobe.mp4" },
  { id: "iq", number: "03", title: "IQ Arena — اختبار الذكاء", subtitle: "اختبار ذكاء تفاعلي", category: "تعليم", description: "تجربة تقييم تفاعلية تبسط اختبار الذكاء عبر أسئلة واضحة، مراحل قصيرة، وإحساس مستمر بالتقدم.", tags: ["Assessment", "Gamification"], cover: "/projects/iq-poster.jpg", kind: "video", asset: "/projects/iq-arena.mp4" },
  { id: "letters", number: "04", title: "حروف ومرح | تعلم الحروف العربية", subtitle: "تعلم الحروف العربية باللعب", category: "تعليم", description: "هوية تعليمية مرحة تساعد الأطفال على اكتشاف الحروف العربية من خلال الصورة والصوت والمكافأة البصرية.", tags: ["Arabic Learning", "Kids UX"], cover: "/assets/playful-letters.jpg", kind: "image", asset: "/assets/playful-letters.jpg" },
  { id: "nuskha", number: "05", title: "نُسخ | مكتبتك، بصوتك", subtitle: "مكتبة صوتية شخصية", category: "ذكاء اصطناعي", description: "واجهة مكتبة صوتية شخصية تُعرض هنا مباشرة داخل الموقع بدل تحويل الزائر إلى Drive.", tags: ["Voice UX", "Library"], cover: "/assets/hero-orbit.jpg", kind: "iframe", asset: "/projects/nuskha.html" },
  { id: "bomberman", number: "06", title: "Bomberman Neon Arcade - لعبة بومبرمان العصرية", subtitle: "لعبة بومبرمان العصرية", category: "ألعاب", description: "نسخة أركيد عصرية من بومبرمان، تُعرض هنا كلعبة HTML مباشرة داخل الموقع.", tags: ["Game Design", "Neon UI"], cover: "/assets/neon-arcade.jpg", kind: "iframe", asset: "/projects/bomberman.html" },
  { id: "whatsapp-video", number: "07", title: "WhatsApp Video 2026-09-16 at 1.25.15 PM.mp4", subtitle: "فيديو من مجلد Hazem Mohammad Khatatneh", category: "فيديو", description: "فيديو مستقل من الرابط الجديد، تمت إضافته إلى البورتفوليو باسمه الفعلي ليعمل مباشرة داخل الموقع.", tags: ["Video", "New Folder"], cover: "/projects/whatsapp-video-poster.jpg", kind: "video", asset: "/projects/whatsapp-video.mp4" },
  { id: "nuskha-package", number: "08", title: "nuskha-site-package.zip", subtitle: "الموقع المستخرج من الملف المضغوط", category: "ذكاء اصطناعي", description: "نسخة الموقع الموجودة داخل الملف المضغوط nuskha-site-package.zip، معروضة مباشرة داخل البورتفوليو.", tags: ["ZIP", "Website"], cover: "/assets/hero-orbit.jpg", kind: "iframe", asset: "/projects/nuskha-package.html" },
  { id: "website-package", number: "09", title: "website-0273b4d9-4405-4106-b120-d49e120d045f.zip", subtitle: "موقع مستخرج من ملف ZIP", category: "ذكاء اصطناعي", description: "الموقع الموجود داخل الملف المضغوط، تم استخراجه وإدراجه كمشروع مستقل باسمه الأصلي.", tags: ["ZIP", "Website"], cover: "/assets/ai-signal.jpg", kind: "iframe", asset: "/projects/website-package.html" },
  { id: "code-artifact", number: "10", title: "code_artifact.html", subtitle: "واجهة ويب تفاعلية", category: "ذكاء اصطناعي", description: "ملف HTML تفاعلي من الملفات المرفقة، يعمل مباشرة داخل نافذة المشروع.", tags: ["HTML", "Interactive"], cover: "/assets/neon-arcade.jpg", kind: "iframe", asset: "/projects/zai.html" },
  { id: "bomberman-source", number: "11", title: "index.html — Bomberman Neon Arcade", subtitle: "ملف اللعبة الأصلي", category: "ألعاب", description: "ملف اللعبة الأصلي كما ورد داخل مجلد Bomberman، معروض داخل الموقع كمشروع مستقل.", tags: ["HTML", "Game"], cover: "/assets/neon-arcade.jpg", kind: "iframe", asset: "/projects/bomberman.html" },
];
const filters: Category[] = ["الكل", "ذكاء اصطناعي", "فيديو", "تعليم", "ألعاب"];
const publicAsset = (path: string) => `${import.meta.env.BASE_URL}${path.replace(/^\//, "")}`;
type Resource = { name: string; type: string; source: string; local?: string };
const resources: Resource[] = [
  { name: "nuskha-site-package.zip — نُسخ", type: "ملف مضغوط / مشروع", source: "https://drive.google.com/file/d/1b6qRICHkAAJydySgEagcQpDO5-Z6yJ5W/view?usp=drivesdk", local: "/projects/nuskha-package.html" },
  { name: "index.html — Bomberman Neon Arcade", type: "مشروع HTML", source: "https://drive.google.com/file/d/1qZ3g5CUwbjt4OknimbKArGZY-wNRP_dF/view?usp=drivesdk", local: "/projects/bomberman.html" },
  { name: "code_artifact.html — مشروع واجهة تفاعلية", type: "مشروع HTML", source: "https://drive.google.com/file/d/1v1E_YgX6TParGCvTN_ENA5Ot14j7Nufo/view?usp=drivesdk", local: "/projects/zai.html" },
  { name: "website-0273b4d9-4405-4106-b120-d49e120d045f.zip", type: "ملف مضغوط / مشروع", source: "https://drive.google.com/file/d/1b5ptPglL588Xtbtm36PQRA-N--fIQdXj/view?usp=drivesdk", local: "/projects/website-package.html" },
  { name: "فيديو بدون عنوان (1).mp4", type: "فيديو مشروع", source: "https://drive.google.com/file/d/13yXxdlZmVw8vIVqCIX80nF4hyXQLuGoZ/view?usp=drivesdk", local: "/projects/wardrobe.mp4" },
  { name: "فيديو بدون عنوان.mp4", type: "فيديو مشروع", source: "https://drive.google.com/file/d/10JFhQVVmdEi17-LduKYy3nc0kxmz0tEd/view?usp=drivesdk", local: "/projects/iq-arena.mp4" },
  { name: "WhatsApp Video 2026-09-16 at 1.25.15 PM.mp4", type: "فيديو مشروع جديد", source: "https://drive.google.com/file/d/1qcrWt9EOXq3nhPQLcDbsIGazhRqxrlGJ/view?usp=drivesdk", local: "/projects/whatsapp-video.mp4" },
  { name: "ElevenLabs_2026-09-15T09_35_24_Sara - Soft, Calm and Gentle.mp3", type: "صوت / تعليق", source: "https://drive.google.com/file/d/1Uf28y-r8fpUPccCyRRT5hJMkrg9YNVEi/view?usp=drivesdk" },
  { name: "Fast_car_engine_revv_#4-1789463612826.mp3", type: "مؤثر صوتي", source: "https://drive.google.com/file/d/1EWls5qnbD_CxHHq1BIw8jlMRtf6O0VyB/view?usp=drivesdk" },
  { name: "Fast_car_engine_revv_#1-1789463433480.mp3", type: "مؤثر صوتي", source: "https://drive.google.com/file/d/1hUb0F3NokEK1pRsOQhjhBHPcY54pw8_T/view?usp=drivesdk" },
  { name: "ElevenLabs_2026-09-15T08_52_11_Liam - Energetic, Social Media Creator.mp3", type: "صوت / تعليق", source: "https://drive.google.com/file/d/1LrPE-spc_4v2AQRN_oe0YYQsrNTKhheS/view?usp=drivesdk" },
  { name: "ElevenLabs_2026-09-15T08_41_41_Liam - Energetic, Social Media Creator (1).mp3", type: "صوت / تعليق", source: "https://drive.google.com/file/d/1BH8Brcd1EaSE5vesP2Q0-suZlcAQ7rrZ/view?usp=drivesdk" },
  { name: "Cheetah_chasing_man_on_trail_20260916132454.mp4", type: "فيديو", source: "https://drive.google.com/file/d/1vYzfkKBSiCncUdCR_yhFo6iDSA_Z0NHT/view?usp=drivesdk" },
  { name: "Boy_superhero_character_turnaround_2K_20260915112101.jpeg", type: "صورة مشروع", source: "https://drive.google.com/file/d/1nHL8Ws22ZwA9LfXaHKNrXC0hCcY11hX8/view?usp=drivesdk" },
  { name: "Untitled design.pdf", type: "ملف تصميم PDF", source: "https://drive.google.com/file/d/15fr1cTUUb5abpBO6qhfldpIN91d_I7AH/view?usp=drivesdk" },
  { name: "Children's_alphabet_book_layout_2K_20260914121708.jpeg", type: "تعليم / حروف", source: "https://drive.google.com/file/d/1MOZy5TzeKkkkOlzYXk1a985ueoLetcGN/view?usp=drivesdk" },
  { name: "Alligator_and_apple_alphabet_page_2K_20260914120950.jpeg", type: "تعليم / حروف", source: "https://drive.google.com/file/d/1IoZOUMCQ74viJPj3uhawCh05GCwv9ZYY/view?usp=drivesdk" },
  { name: "Bumblebee_hovering_over_blue_flower_2K_20260914120932.jpeg", type: "صورة مولدة", source: "https://drive.google.com/file/d/167XwYON_4uiRe3gahX1JRObhGJxkn6U4/view?usp=drivesdk" },
  { name: "Color, Create, and Smile!.jpg", type: "تعليم / أطفال", source: "https://drive.google.com/file/d/1s24GzJZ-dbUEZ-HTkZwAJHtGhurCgf21/view?usp=drivesdk" },
  { name: "Coloring book_ For kids.jpg", type: "تعليم / أطفال", source: "https://drive.google.com/file/d/1tRLfeX2WhbY3odZTTqXMbIh5t4ZI1Wsa/view?usp=drivesdk" },
  { name: "Building a World of Dreams, One Story at a Time.jpg", type: "قصة / إبداع", source: "https://drive.google.com/file/d/1_DAgNgqvzwjPjCOk16RDAJ8Z6cSCLmCL/view?usp=drivesdk" },
  { name: "The Tiny Firefly Who Taught a Big Lesson.jpg", type: "قصة / أطفال", source: "https://drive.google.com/file/d/1rK3z2-HG6jt7vRZ6t3bXam1KC3faXDxW/view?usp=drivesdk" },
  { name: "Bowl_of_noodles_on_table_2K_20260914111320.jpeg", type: "صورة مولدة", source: "https://drive.google.com/file/d/1vPTZCugF10fPWu_4bGxqTr0bYZtlrpog/view?usp=drivesdk" },
  { name: "Cairo_Skyward.mp3", type: "موسيقى / صوت", source: "https://drive.google.com/file/d/1cfTg-h8PwE9d1UK12cfLeNwznMnhhtZ9/view?usp=drivesdk" },
  { name: "بلا عنوان — مستند Google", type: "مستند", source: "https://docs.google.com/document/d/10X8wP7qmt43p3BFGEFXYHxI_JCIOjbwR6Ze3jzKmhIU/edit" },
  { name: "ليان وطائر الأسرار الذهبي.pdf", type: "قصة PDF", source: "https://drive.google.com/file/d/1faKvSnlg_CxW8skR1JWSswcCTY0hu0Fv/view?usp=drivesdk" },
  { name: "Gemini_Generated_Image_lzbmualzbmualzbm.jpg", type: "صورة مولدة", source: "https://drive.google.com/file/d/15q3qBDk_cLMunymdQ0QwMyrkLdY6kLWe/view?usp=drivesdk" },
  { name: "Gemini_Generated_Image_l1tte8l1tte8l1tt.jpg", type: "صورة مولدة", source: "https://drive.google.com/file/d/16tETklFV16mhB4qZyaaugcJ0L39h_HW0/view?usp=drivesdk" },
  { name: "WhatsApp Image 2026-09-13 at 12.23.04 PM.jpeg", type: "صورة", source: "https://drive.google.com/file/d/1HTHyItQkij_9sMg4EFXD8nAN-zp-zhWp/view?usp=drivesdk" },
  { name: "designarena_image_q1tp9qny.png", type: "صورة مشروع", source: "https://drive.google.com/file/d/1zUHsYUgQCySgdTIDiViLur032brP6RX2/view?usp=drivesdk" },
  { name: "السيرة الذاتية — CV", type: "ملف مهني", source: "https://docs.google.com/document/d/1_TsbarR5Xiot3jjqudcZB7eahedKHEwm/edit" },
  { name: "مرجع عملي.docx", type: "مرجع معلومات", source: "https://docs.google.com/document/d/1Pg8k3yBEzPLi1mCTebJsRkrp4A8B3wbP/edit" },
];

function SectionTitle({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) {
  return <div className="section-title"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</div>;
}

export default function Home() {
  const [filter, setFilter] = useState<Category>("الكل");
  const [selected, setSelected] = useState<Project | null>(null);
  const [menuOpen, setMenuOpen] = useState(false);
  const visible = useMemo(() => filter === "الكل" ? projects : projects.filter((p) => p.category === filter), [filter]);
  const scrollTo = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); setMenuOpen(false); };
  return <main dir="rtl" className="traditional-site">
    <header className="site-header"><button className="wordmark" onClick={() => scrollTo("home")}><span className="wordmark-seal">H</span><span><b>Hazem Mohammad Khatatneh</b><small>COMPUTER SCIENCE · PORTFOLIO 2026</small></span></button><nav className={menuOpen ? "main-nav is-open" : "main-nav"}><button onClick={() => scrollTo("home")}>الرئيسية</button><button onClick={() => scrollTo("projects")}>المشاريع</button><button onClick={() => scrollTo("archive")}>الفهرس</button><button onClick={() => scrollTo("about")}>نبذة عنّي</button><button onClick={() => scrollTo("cv")}>سيرة ذاتية</button><button onClick={() => scrollTo("contact")}>تواصل</button></nav><div className="header-side"><span className="availability"><i /> متاح للتعاون</span><button className="menu-toggle" onClick={() => setMenuOpen((v) => !v)}>{menuOpen ? <X size={19} /> : <Menu size={19} />}</button></div></header>
    <section id="home" className="hero-traditional"><div className="hero-rule" /><div className="hero-copy-traditional"><span className="eyebrow">Computer Science · Lecturer · Digital Creator</span><h1>أحوّل الفكرة<br /><em>إلى أثر.</em></h1><p>أنا <strong>Hazem Mohammad Khatatneh</strong>، محاضر علوم حاسوب وصانع تجارب رقمية، أعمل عند نقطة التقاء التقنية والتعليم والإبداع لصناعة تجارب واضحة، جميلة، وقابلة للاستخدام.</p><div className="hero-actions-traditional"><button className="button-primary" onClick={() => scrollTo("projects")}>استعرض المشاريع <ArrowLeft size={17} /></button><a className="text-link" href="mailto:hazem.now55@gmail.com">ابدأ محادثة <ChevronLeft size={16} /></a></div></div><div className="hero-card"><div className="hero-card-image" style={{ backgroundImage: `url(${publicAsset("/assets/hero-orbit.jpg")})` }} /><div className="hero-card-caption"><span>01</span><span>IDEA · DESIGN · BUILD</span></div></div><div className="hero-bottom"><span>AMMAN · JORDAN</span><span>HAZEM MOHAMMAD KHATATNEH</span><span>مرّر لاكتشاف الأعمال ↓</span></div></section>
    <section id="projects" className="content-section projects-section"><SectionTitle eyebrow="01 / مختارات من الأعمال" title="مشاريع مبنية لتُعرض، لا لتُحفظ." copy="الملفات التفاعلية والفيديوهات والألعاب والمواقع المعروضة هنا مستضافة داخل الموقع نفسه." /><div className="filter-row"><div className="filter-label"><Filter size={16} /> تصفية المشاريع</div><div className="filters">{filters.map((item) => <button key={item} className={filter === item ? "selected" : ""} onClick={() => setFilter(item)}>{item}<small>{item === "الكل" ? String(projects.length).padStart(2, "0") : String(projects.filter((p) => p.category === item).length).padStart(2, "0")}</small></button>)}</div></div><div className="projects-list">{visible.map((project) => <article className="traditional-project-card" key={project.id} onClick={() => setSelected(project)}><div className="project-cover"><img src={publicAsset(project.cover)} alt="" /><span className="project-number">{project.number} / {String(projects.length).padStart(2, "0")}</span><span className="project-open">عرض المشروع <ArrowLeft size={16} /></span></div><div className="project-card-body"><div><span className="project-category">{project.category}</span><h3>{project.title}</h3><p>{project.subtitle}</p></div><ChevronLeft className="card-arrow" size={21} /></div><div className="project-tags">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></article>)}</div></section>
    <section id="archive" className="archive-section content-section"><SectionTitle eyebrow="02 / الفهرس الكامل" title="كل الملفات، بأسمائها الفعلية." copy="فهرس متسلسل لمحتويات الرابطين المرفقين والملفات المضغوطة. الملفات التي أمكن عرضها مباشرة تفتح داخل الموقع، وبقية الملفات تفتح مصدرها الأصلي." /><div className="resource-list">{resources.map((item, index) => <a className="resource-row" key={item.name} href={item.local ? publicAsset(item.local) : item.source} target={item.local ? "_self" : "_blank"} rel={item.local ? undefined : "noreferrer"}><span className="resource-index">{String(index + 1).padStart(2, "0")}</span><span className="resource-name"><b>{item.name}</b><small>{item.type}</small></span><span className="resource-open">{item.local ? "عرض داخل الموقع" : "فتح الملف"} <ArrowLeft size={15} /></span></a>)}</div></section>
    <section id="about" className="about-traditional content-section"><div className="about-side"><span>03</span><b>نبذة</b></div><div><SectionTitle eyebrow="03 / خلف الخبرة" title="خبرة تقنية، وحسّ إنساني." /><div className="about-columns"><p>بدأت رحلتي من علوم الحاسوب، ثم امتدت إلى قاعات التدريب وتصميم التجارب التي تجعل المعرفة أسهل وأقرب. أؤمن أن التصميم الجيد لا يشرح نفسه فقط، بل يترك أثرًا واضحًا.</p><p>أمتلك خبرة طويلة في تدريس علوم الحاسوب، وأعمل عبر Java وC++ وHTML وSQL وCCNA، مع اهتمام خاص بالذكاء الاصطناعي والألعاب والصوت والتعليم.</p></div><div className="facts"><div><Briefcase size={19} /><b>10+<small>سنوات في التعليم</small></b></div><div><FileText size={19} /><b>06<small>مشاريع مختارة</small></b></div><div><Check size={19} /><b>RTL<small>تجارب عربية أولًا</small></b></div></div></div></section>
    <section id="cv" className="cv-section content-section"><div className="about-side"><span>04</span><b>سيرة ذاتية</b></div><div><SectionTitle eyebrow="04 / سيرة ذاتية" title="Hazem Mohammad Khatatneh" copy="Computer Science lecturer with academic experience and practical digital projects." /><div className="cv-grid"><div><small>التخصص</small><b>Computer Science / Computer Information Systems</b></div><div><small>المؤهل العلمي</small><b>Master Degree — Computer Information System · MEU · 2012</b></div><div><small>المؤهل السابق</small><b>B.Sc. Computer Information System — Mutah University · 2006</b></div><div><small>الخبرة</small><b>Computer Lecturer in Jordan and Saudi Arabia</b></div><div><small>المهارات</small><b>Java · C++ · HTML · SQL · Oracle · CCNA · Blackboard</b></div><div><small>اللغات</small><b>Arabic — Native · English — Good</b></div></div></div></section>
    <section id="contact" className="contact-traditional content-section"><span className="eyebrow">05 / تواصل</span><h2>هل لديك فكرة<br /><em>تستحق التنفيذ؟</em></h2><p>للتعاون، التدريس، أو مشروع رقمي يريد أن يخرج عن المألوف.</p><a className="contact-button" href="mailto:hazem.now55@gmail.com"><Mail size={18} /> hazem.now55@gmail.com <ArrowLeft size={17} /></a><footer><span>© 2026 Hazem Mohammad Khatatneh</span><span>صُمم ونُفذ بعناية في عمّان</span></footer></section>
    {selected && <div className="project-dialog-backdrop" onClick={() => setSelected(null)}><div className="project-dialog" onClick={(event) => event.stopPropagation()}><button className="dialog-close" onClick={() => setSelected(null)}><X size={19} /></button><div className="dialog-heading"><span className="eyebrow">{selected.number} / عرض مباشر</span><h2>{selected.title}</h2><p>{selected.description}</p></div><div className="direct-preview">{selected.kind === "video" && <video src={publicAsset(selected.asset)} poster={publicAsset(selected.cover)} controls playsInline />}{selected.kind === "image" && <img src={publicAsset(selected.asset)} alt={selected.title} />}{selected.kind === "iframe" && <iframe src={publicAsset(selected.asset)} title={selected.title} />}</div><div className="dialog-footer"><div className="project-tags">{selected.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><span><Play size={14} /> معروض داخل الموقع مباشرة</span></div></div></div>}
  </main>;
}
