import { useMemo, useState } from "react";
import { ArrowLeft, Briefcase, Check, ChevronLeft, FileText, Filter, Mail, Menu, Play, X } from "lucide-react";

type Category = "الكل" | "ذكاء اصطناعي" | "فيديو" | "تعليم" | "ألعاب";
type Project = { id: string; number: string; title: string; subtitle: string; category: Exclude<Category, "الكل">; description: string; tags: string[]; cover: string; kind: "iframe" | "video" | "image"; asset: string };

const projects: Project[] = [
  { id: "zai", number: "01", title: "Z.ai", subtitle: "مساعد ذكاء اصطناعي ووكلاء رقميون", category: "ذكاء اصطناعي", description: "تجربة مباشرة لمساعد ذكي متقدم مدعوم بـ GLM-5.3-Flash، تجمع بين الحوار والتفكير وتنفيذ المهام.", tags: ["GLM-5.3-Flash", "AI Agent"], cover: "/assets/ai-signal.jpg", kind: "iframe", asset: "/projects/zai.html" },
  { id: "wardrobe", number: "02", title: "خزانة ملابس بتقنية عالية", subtitle: "فيلم بصري من Manus", category: "فيديو", description: "فيديو إبداعي يعرض تصورًا بصريًا لخزانة ملابس ذكية، مع معالجة سينمائية وإخراج بصري مولد بالذكاء الاصطناعي.", tags: ["AI Video", "Art Direction"], cover: "/projects/wardrobe-poster.jpg", kind: "video", asset: "/projects/wardrobe.mp4" },
  { id: "iq", number: "03", title: "IQ Arena", subtitle: "اختبار ذكاء تفاعلي", category: "تعليم", description: "تجربة تقييم تفاعلية تبسط اختبار الذكاء عبر أسئلة واضحة، مراحل قصيرة، وإحساس مستمر بالتقدم.", tags: ["Assessment", "Gamification"], cover: "/projects/iq-poster.jpg", kind: "video", asset: "/projects/iq-arena.mp4" },
  { id: "letters", number: "04", title: "حروف ومرح", subtitle: "تعلم الحروف العربية باللعب", category: "تعليم", description: "هوية تعليمية مرحة تساعد الأطفال على اكتشاف الحروف العربية من خلال الصورة والصوت والمكافأة البصرية.", tags: ["Arabic Learning", "Kids UX"], cover: "/assets/playful-letters.jpg", kind: "image", asset: "/assets/playful-letters.jpg" },
  { id: "nuskha", number: "05", title: "نُسخ", subtitle: "مكتبتك، بصوتك", category: "ذكاء اصطناعي", description: "واجهة مكتبة صوتية شخصية تُعرض هنا مباشرة داخل الموقع بدل تحويل الزائر إلى Drive.", tags: ["Voice UX", "Library"], cover: "/assets/hero-orbit.jpg", kind: "iframe", asset: "/projects/nuskha.html" },
  { id: "bomberman", number: "06", title: "Bomberman Neon Arcade", subtitle: "لعبة بومبرمان العصرية", category: "ألعاب", description: "نسخة أركيد عصرية من بومبرمان، تُعرض هنا كلعبة HTML مباشرة داخل الموقع.", tags: ["Game Design", "Neon UI"], cover: "/assets/neon-arcade.jpg", kind: "iframe", asset: "/projects/bomberman.html" },
];
const filters: Category[] = ["الكل", "ذكاء اصطناعي", "فيديو", "تعليم", "ألعاب"];
const publicAsset = (path: string) => `${import.meta.env.BASE_URL}${path.replace(/^\//, "")}`;

function SectionTitle({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) {
  return <div className="section-title"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</div>;
}

export default function Home() {
  const [filter, setFilter] = useState<Category>("الكل");
  const [selected, setSelected] = useState<Project | null>(null);
  const [menuOpen, setMenuOpen] = useState(false);
  const visible = useMemo(() => filter === "الكل" ? projects : projects.filter((p) => p.category === filter), [filter]);
  const scrollTo = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); setMenuOpen(false); };
  return <main dir="rtl" className="traditional-site">
    <header className="site-header"><button className="wordmark" onClick={() => scrollTo("home")}><span className="wordmark-seal">ح</span><span><b>حازم محمد خطابنة</b><small>PORTFOLIO · 2026</small></span></button><nav className={menuOpen ? "main-nav is-open" : "main-nav"}><button onClick={() => scrollTo("home")}>الرئيسية</button><button onClick={() => scrollTo("projects")}>المشاريع</button><button onClick={() => scrollTo("about")}>نبذة عنّي</button><button onClick={() => scrollTo("contact")}>تواصل</button></nav><div className="header-side"><span className="availability"><i /> متاح للتعاون</span><button className="menu-toggle" onClick={() => setMenuOpen((v) => !v)}>{menuOpen ? <X size={19} /> : <Menu size={19} />}</button></div></header>
    <section id="home" className="hero-traditional"><div className="hero-rule" /><div className="hero-copy-traditional"><span className="eyebrow">مصمم تجارب رقمية · محاضر علوم حاسوب</span><h1>أحوّل الفكرة<br /><em>إلى أثر.</em></h1><p>أنا <strong>حازم محمد خطابنة</strong>، أعمل عند نقطة التقاء التقنية والتعليم والإبداع لصناعة تجارب واضحة، جميلة، وقابلة للاستخدام.</p><div className="hero-actions-traditional"><button className="button-primary" onClick={() => scrollTo("projects")}>استعرض المشاريع <ArrowLeft size={17} /></button><a className="text-link" href="mailto:hazem.now55@gmail.com">ابدأ محادثة <ChevronLeft size={16} /></a></div></div><div className="hero-card"><div className="hero-card-image" style={{ backgroundImage: `url(${publicAsset("/assets/hero-orbit.jpg")})` }} /><div className="hero-card-caption"><span>01</span><span>فكرة · تصميم · تنفيذ</span></div></div><div className="hero-bottom"><span>AMMAN · JORDAN</span><span>بورتفوليو شخصي</span><span>مرّر لاكتشاف الأعمال ↓</span></div></section>
    <section id="projects" className="content-section projects-section"><SectionTitle eyebrow="01 / مختارات من الأعمال" title="مشاريع مبنية لتُعرض، لا لتُحفظ." copy="الملفات التفاعلية والفيديوهات المعروضة هنا مستضافة داخل الموقع نفسه، وليست روابط تحولك إلى Drive." /><div className="filter-row"><div className="filter-label"><Filter size={16} /> تصفية المشاريع</div><div className="filters">{filters.map((item) => <button key={item} className={filter === item ? "selected" : ""} onClick={() => setFilter(item)}>{item}<small>{item === "الكل" ? "06" : String(projects.filter((p) => p.category === item).length).padStart(2, "0")}</small></button>)}</div></div><div className="projects-list">{visible.map((project) => <article className="traditional-project-card" key={project.id} onClick={() => setSelected(project)}><div className="project-cover"><img src={publicAsset(project.cover)} alt="" /><span className="project-number">{project.number} / 06</span><span className="project-open">عرض المشروع <ArrowLeft size={16} /></span></div><div className="project-card-body"><div><span className="project-category">{project.category}</span><h3>{project.title}</h3><p>{project.subtitle}</p></div><ChevronLeft className="card-arrow" size={21} /></div><div className="project-tags">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></article>)}</div></section>
    <section id="about" className="about-traditional content-section"><div className="about-side"><span>02</span><b>نبذة</b></div><div><SectionTitle eyebrow="02 / خلف الخبرة" title="خبرة تقنية، وحسّ إنساني." /><div className="about-columns"><p>بدأت رحلتي من علوم الحاسوب، ثم امتدت إلى قاعات التدريب وتصميم التجارب التي تجعل المعرفة أسهل وأقرب. أؤمن أن التصميم الجيد لا يشرح نفسه فقط، بل يترك أثرًا واضحًا.</p><p>أمتلك خبرة طويلة في تدريس علوم الحاسوب، وأعمل عبر Java وC++ وHTML وSQL وCCNA، مع اهتمام خاص بالذكاء الاصطناعي والألعاب والصوت والتعليم.</p></div><div className="facts"><div><Briefcase size={19} /><b>10+<small>سنوات في التعليم</small></b></div><div><FileText size={19} /><b>06<small>مشاريع مختارة</small></b></div><div><Check size={19} /><b>RTL<small>تجارب عربية أولًا</small></b></div></div></div></section>
    <section id="contact" className="contact-traditional content-section"><span className="eyebrow">03 / تواصل</span><h2>هل لديك فكرة<br /><em>تستحق التنفيذ؟</em></h2><p>للتعاون، التدريس، أو مشروع رقمي يريد أن يخرج عن المألوف.</p><a className="contact-button" href="mailto:hazem.now55@gmail.com"><Mail size={18} /> hazem.now55@gmail.com <ArrowLeft size={17} /></a><footer><span>© 2026 حازم محمد خطابنة</span><span>صُمم ونُفذ بعناية في عمّان</span></footer></section>
    {selected && <div className="project-dialog-backdrop" onClick={() => setSelected(null)}><div className="project-dialog" onClick={(event) => event.stopPropagation()}><button className="dialog-close" onClick={() => setSelected(null)}><X size={19} /></button><div className="dialog-heading"><span className="eyebrow">{selected.number} / عرض مباشر</span><h2>{selected.title}</h2><p>{selected.description}</p></div><div className="direct-preview">{selected.kind === "video" && <video src={publicAsset(selected.asset)} poster={publicAsset(selected.cover)} controls playsInline />}{selected.kind === "image" && <img src={publicAsset(selected.asset)} alt={selected.title} />}{selected.kind === "iframe" && <iframe src={publicAsset(selected.asset)} title={selected.title} />}</div><div className="dialog-footer"><div className="project-tags">{selected.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><span><Play size={14} /> معروض داخل الموقع مباشرة</span></div></div></div>}
  </main>;
}
